<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Hevy.Client.Models" />
    <ProjectReference Include="../../src/Hevy.Mcp/Hevy.Mcp.csproj" />
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentAssertions.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime;build;native;contentfiles;analyzers;buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime;build;native;contentfiles;analyzers;buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../TestSupport/FakeHevyClient.cs" Link="TestSupport/FakeHevyClient.cs" />
    <Compile Include="../TestSupport/FixtureFactory.cs" Link="TestSupport/FixtureFactory.cs" />
    <Compile Include="../TestSupport/McpStdioProcess.cs" Link="TestSupport/McpStdioProcess.cs" />
  </ItemGroup>
</Project>
