using System.Text.Json.Serialization;
using Hevy.Client.Models;

namespace Hevy.Client.Serialization;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    UseStringEnumConverter = true)]
[JsonSerializable(typeof(Workout))]
[JsonSerializable(typeof(WorkoutPage))]
[JsonSerializable(typeof(WorkoutCountResponse))]
[JsonSerializable(typeof(WorkoutEventsPage))]
[JsonSerializable(typeof(Routine))]
[JsonSerializable(typeof(RoutinePage))]
[JsonSerializable(typeof(RoutineResponse))]
[JsonSerializable(typeof(RoutineFolder))]
[JsonSerializable(typeof(RoutineFolderPage))]
[JsonSerializable(typeof(ExerciseTemplate))]
[JsonSerializable(typeof(ExerciseTemplatePage))]
[JsonSerializable(typeof(CreateExerciseTemplateResponse))]
[JsonSerializable(typeof(ExerciseHistoryEntry))]
[JsonSerializable(typeof(ExerciseHistoryResponse))]
[JsonSerializable(typeof(BodyMeasurement))]
[JsonSerializable(typeof(BodyMeasurementPage))]
[JsonSerializable(typeof(UserInfo))]
[JsonSerializable(typeof(UserInfoResponse))]
[JsonSerializable(typeof(UpdatedWorkoutEvent))]
[JsonSerializable(typeof(DeletedWorkoutEvent))]
[JsonSerializable(typeof(CreateWorkoutRequest))]
[JsonSerializable(typeof(UpdateWorkoutRequest))]
[JsonSerializable(typeof(WorkoutWrite))]
[JsonSerializable(typeof(WorkoutExerciseWrite))]
[JsonSerializable(typeof(WorkoutSetWrite))]
[JsonSerializable(typeof(CreateRoutineRequest))]
[JsonSerializable(typeof(UpdateRoutineRequest))]
[JsonSerializable(typeof(CreateRoutineWrite))]
[JsonSerializable(typeof(UpdateRoutineWrite))]
[JsonSerializable(typeof(CreateRoutineExerciseWrite))]
[JsonSerializable(typeof(UpdateRoutineExerciseWrite))]
[JsonSerializable(typeof(CreateRoutineSetWrite))]
[JsonSerializable(typeof(UpdateRoutineSetWrite))]
[JsonSerializable(typeof(CreateRoutineRepRange))]
[JsonSerializable(typeof(CreateRoutineFolderRequest))]
[JsonSerializable(typeof(RoutineFolderWrite))]
[JsonSerializable(typeof(CreateExerciseTemplateRequest))]
[JsonSerializable(typeof(CustomExerciseWrite))]
[JsonSerializable(typeof(CreateBodyMeasurementRequest))]
[JsonSerializable(typeof(UpdateBodyMeasurementRequest))]
public sealed partial class HevyJsonContext : JsonSerializerContext;
